# Generated by Django 4.0.6 on 2022-07-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_teache_mattendences_remove_attendance_periods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
